### ISSUE TITLE
Commit Count

### ISSUE THREAD

**Issue by Symbianx** [WCOMAB/Cake_Git#13]
Hello, in our build process we identify builds with the commit count using the output from command `git rev-list --all --count`. 
Is it possible to get the repo commit count using this Addin?

**Comment by devlead** [comment]
Yes that's certainly possible example:
```cake
#addin nuget:?package=Cake.Git

DirectoryPath repoPath = Directory("path to repo");

var commits = GitLog(repoPath, int.MaxValue);

Information("Number of commits: {0}", commits.Count);
```
will out put something like
```
Number of commits: 1539
```

**Comment by Symbianx** [comment]
Thanks for the fast reply, didn't see the GitLog method. Next time I'll have to take a closer look at the docs! :)
