### ISSUE TITLE
Exception on OS X

### ISSUE THREAD

**Issue by krippz** [WCOMAB/Cake_Git#2]
Seems lib2git does not play nice with OS X :(

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: git2-785d8c4

Mono, version
Mono JIT compiler version 4.2.3 (explicit/832de4b Thu Mar  3 19:24:57 EST 2016)

**Comment by devlead** [comment]
@krippz this should be solved in version 0.2.0
