### ISSUE TITLE
Add examples for GitPush

### ISSUE THREAD

**Issue by gep13** [WCOMAB/Cake_Git#21]
That flow through to the Cake Website.

Based on discussion here:

https://gitter.im/cake-build/cake?at=58384e00444b377876562e83

**Comment by phillipsj** [comment]
@gep13 Should this be to add examples for all the commands?

**Comment by devlead** [comment]
Ultimately all aliases should have examples.

**Comment by phillipsj** [comment]
If I find some time I will submit a PR shouldn't take very long to do.

**Comment by gep13** [comment]
Yes, would be ultimately for all aliases. This was just a quick issue based on the gutter discussion.

**Comment by devlead** [comment]
@phillipsj perfect, think many of the aliases have examples in [test.cake](https://github.com/WCOMAB/Cake_Git/blob/master/test.cake)
