### ISSUE TITLE
GitPull throws Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by xdinos** [WCOMAB/Cake_Git#24]
Hi,
I'm trying to execute 
`var gitMergeResult = GitPull(path, mergerName, mergerEmail, username, password, "origin");`
and I'm getting an `Object reference not set to an instance of an object.` exception.

**Comment by stefandevo** [comment]
Same here...

**Comment by devlead** [comment]
Which version of Cake&Cake.Git and which OS and version of it ate you using?

**Comment by stefandevo** [comment]
All latest versions, Windows.

**Comment by devlead** [comment]
Does running cake with diagnostic verbosity give you a more detailed stacktrace?

**Comment by devlead** [comment]
Can repro it, will see if I can submit a patch.

**Comment by devlead** [comment]
@stefandevo a new version that fixes this issue has just now been submitted to nuget.org and should be indexed shortly
https://www.nuget.org/packages/Cake.Git/0.12.0
