### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by matkoch** [WCOMAB/Cake_Git#36]
I'm not completely sure, but isn't the resulting nupkg violating the license of libgit? It contains the executables rather than a package dependency.

**Comment by devlead** [comment]
Libgit2sharp is MIT, libgit2 is GPLv2 but has a linking exception
```
....
LINKING EXCEPTION

 In addition to the permissions in the GNU General Public License,
 the authors give you unlimited permission to link the compiled
 version of this library into combinations with other programs,
 and to distribute those combinations without any restriction
...
```

**Comment by matkoch** [comment]
Yes, but you're not redistributing the license or a reference to it.

**Comment by matkoch** [comment]
>     You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

**Comment by devlead** [comment]
Then we should correct that.

**Comment by devlead** [comment]
With v0.15.0 license now included in nuget with links to original licenses.
