### ISSUE TITLE
Error when running on TeamCity

### ISSUE THREAD

**Issue by johnkors** [WCOMAB/Cake_Git#38]
Hi, 

Getting the following build error when trying to run `GitBranchCurrent` on TeamCity, but not locally.

```
Error: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
[10:57:23][Step 1/1] Unhandled Exception: System.TypeInitializationException: 
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. 
---> System.DllNotFoundException: 
Unable to load DLL 'git2-1196807': The specified module could not be found. 
(Exception from HRESULT: 0x8007007E)
```

Any workaround..?

**Comment by devlead** [comment]
Which version of cake & cake git is running on the server?
Which OS and. NET framework is running on the server?

**Comment by johnkors** [comment]
Cake: `<package id="Cake" version="0.19.5" />`
Cake.GIt `#addin nuget:?package=Cake.Git` (so latest, I presume)
OS: Windows Server 2012 R2, version 6.3
.NET:  
  * Full Framework .NET 2.0 / .NET 3.5 / .NET 4.0 (4.5, 4.5.1, 4.6.1, 4.6.2)
  * .NET Core: 1.0.0-preview2(*), 1.0.1, 2.0.0-preview*

**Comment by johnkors** [comment]
![image](https://cloud.githubusercontent.com/assets/206726/26541192/026cbebe-4455-11e7-8603-71d472584ead.png)

Seems the win32 folder is missing alltogether on the build agent. Strange.

**Comment by johnkors** [comment]
Resolved. My mistake.

My error was with having the `/tools` folder generated by Cake checked into source control. In conjunction with a standard GitHub [.gitignore for VisualStudio](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore#L20), I _think_ the `/x64 / x86` 
 dlls Cake.Git needs was never included into source control from the beginning.

Further on, one needs to have set the build agent VCS settings to `Automatically on agent` to have the working dir include the `.git` folder for it to work.

**Comment by devlead** [comment]
ok, glad it got sorted and thanks for getting back to us.
