### ISSUE TITLE
Add alias for git tag 

### ISSUE THREAD

**Issue by jblazek** [WCOMAB/Cake_Git#8]
Our release process, we use git tag to create a tag from the release was deployed from.  

Is it possible to add a new alias for tagging?

**Comment by devlead** [comment]
Yes it's certainly possible it's the ApplyTag method on repo.
https://github.com/libgit2/libgit2sharp/wiki/git-tag#creating-tags

**Comment by devlead** [comment]
@jblazek added into 0.7.0 uploaded and will shortly be available on nuget
https://www.nuget.org/packages/Cake.Git/0.7.0

You can see usage here
https://github.com/WCOMAB/Cake_Git/blob/master/test.cake#L313-L325

**Comment by jblazek** [comment]
@devlead thanks for the quick response!
