### ISSUE TITLE
Add alias for git push with refspec

### ISSUE THREAD

**Issue by jblazek** [WCOMAB/Cake_Git#9]
As part of our build workflow, we push a tag to a remote.  Currently, it seems like the Cake.Git only supports pushing branches.  

The helper code I wrote to do this looks like the following 
```cs
static class GitExt {
	public static void Push(DirectoryPath repositoryPath, string remote, string refSpec) {
		using (var repository = new LibGit2Sharp.Repository(repositoryPath.FullPath))
		{
			repository.Network.Push(repository.Network.Remotes[remote], refSpec);
		}
	}
}
```

The cake build task I use then calls the helper code like below:
```cs
Task("Push-Release-Tag")
	.WithCriteria(isReleaseRequested)
	.WithCriteria(!noPush)
	.Does(() => {
		var tagVersion = "v" + releaseVersion;
		string gitRemote = "origin";
		Information("Pushing new tag to {0}", gitRemote);
		GitExt.Push(".", gitRemote, "refs/tags/" + tagVersion);
	});
```

This seems like the type of thing that would be useful to include with the Cake.Addin, would this be something that could be added?

**Comment by devlead** [comment]
Yes that would be an great addition to Cake.Git, and I'll happily review a PR for that.

Could probably add an GitPushTag alias too, that utilizes this and does the `$"refs/tags/{tagName}"` magic too.
